drivers/: video/mt6768: Fix a wstrict prototypes
*
../drivers/misc/mediatek/video/mt6768/dispsys/display_recorder.c:1127:33:
error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]

Change-Id: Idf375e7409fbb0cdf0859c7e09e15155810e53bc